---
deployment:
    tasks:
        - echo "Updating repository in $(pwd)"
        - git pull origin main  # Replace 'main' with your default branch name
        - echo "Repository updated successfully!"